### ISSUE TITLE
Required C18 for Linux 64-bit

### ISSUE THREAD

**Issue by chennakeshavaSoC** [Manouchehri/Microchip-C18-Lite#1]
Hi Manouchehri,

Is it possible to get a C18 compiler for 64-bit Linux (Ubuntu 12.04 LTS).

**Comment by chennakeshavaSoC** [comment]
Found the root cause, I was executing it from a windows partition.
After moving it to linux home folder, it got installed.

**Comment by Manouchehri** [comment]
@chennakeshavaSoC Run `chmod +x mplabc18-v3.47-linux-lite-installer.run` to mark it as executable.
